### ISSUE TITLE
Criação dos times

### ISSUE THREAD

**Issue by yrosaguiar** [yros-cloud/mentoria#6]
Precisamos dividir as pessoas em grupos de no maximo 3 pessoas, Precisamos definir um nome.

**Comment by riks88** [comment]
separar times por nomes inspirados em star wars

**Comment by luisfroliveira** [comment]
Cavaleiros do Zodíaco

**Comment by yrosaguiar** [comment]
Acho importante cada time ter pessoas com níveis de conhecimento diferente

**Comment by reysonbarros** [comment]
Sugestão de nome para o time:
EngenheirosDoAmanha

Vamos lá galera! Sugiram nomes também.

**Comment by AnaCandida** [comment]
Pra ajudar um pouco, a gente da um tema e ele devolve algumas ideias: https://namify.tech/suggestions

**Comment by yrosaguiar** [comment]
Vamos separar os times dai o time decide, acho que faz mais sentido
